name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  # These 3 jobs run in PARALLEL
  security:
    name: Security Scan
    uses: pblsnchzrmro/terraform-shared-workflows/.github/workflows/security-scan.yml@main

  pre-commit:
    name: Pre-Commit Validation
    uses: pblsnchzrmro/terraform-shared-workflows/.github/workflows/pre-commit.yml@main

  docs:
    name: Generate Documentation
    uses: pblsnchzrmro/terraform-shared-workflows/.github/workflows/doc.yml@main
