name: Run security scan

on:
  workflow_call:

jobs:
  kics:
    name: Run security scan
    runs-on: "ubuntu-latest"

    steps:
    - name: Checkout code repo
      uses: actions/checkout@v5

    - name: Security KICS scanner
      uses: checkmarx/kics-github-action@v2.1.15
      with:
        path: .
        output_path: securityResults/
        output_formats: 'sarif'
        enable_comments: true
        enable_annotations: true
        ignore_on_exit: results
       
